const data = {
    products:[
        {
            _id:'1',
            name:'Summer Slim Nike Shirt',
            category: 'Shirts',
            image: 'images/p1.jpg',
            price: 1000,
            countInStock: 0,
            brand: 'Al Mayas',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Leto Al Mayas Shirt',
            category: 'Shirts',
            image: 'images/p1.jpg',
            price: 1100,
            countInStock: 30,
            brand: 'Al Mayas',
            rating: 4.3,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'resil almayas Shirt',
            category: 'Shirts',
            image: 'images/p1.jpg',
            price: 1200,
            countInStock: 15,
            brand: 'Al Mayas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Summer wear Almayas Shirt',
            category: 'Shirts',
            image: 'images/p1.jpg',
            price: 1200,
            countInStock: 17,
            brand: 'Al Mayas',
            rating: 4.7,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Summer Al mayas Shirt',
            category: 'Shirts',
            image: 'images/p1.jpg',
            price: 1000,
            countInStock: 34,
            brand: 'Al Mayas',
            rating: 4.1,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Summer Slim Al Mayas Shirt',
            category: 'Shirts',
            image: 'images/p1.jpg',
            price: 1200,
            countInStock: 23,
            brand: 'Al Mayas',
            rating: 4.1,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'7',
            name:'Summer Teeno Al Mayas Shirt',
            category: 'Shirts',
            image: 'images/p1.jpg',
            price: 1200,
            countInStock: 19,
            brand: 'Al Mayas',
            rating: 4.3,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};

export default data;